### ISSUE TITLE
Feedback Camille

### ISSUE THREAD

**Issue by blatinier** [blatinier/onestpasdespigeons#79]
- [ ] Pagination my/all measure couleur
- [ ] Filter moche
- [ ] Add measure btn (postion & color)
- [ ] add measure tpl

### Template/CSS
- [x] Page d'accueil agrandir la photographie + info qui vont avec quand on clique dessus
- [x] Le pourcentage de perte ou d'ajout devrait être mieux mis en valeur, réfléchir au graphisme pour qu'il soit bien visible
- [x] Qui sommes nous ? une jolie photographie de vous deux séparément ou ensemble ça se réfléchit avec une vraie présentation qui donne envie du type "Benoît est ingénieur en informatique sur les routes du monde avec sa famille...) ex : photo au milieu, à gauche présentation de Fabien, à droite pésentation de Benoît 
- [x] Connexion : travailler le design pour rendre la page plus accueillante
- [x] Dans la partie "toutes les mesures" trouver deux écritures différentes (ou couleur, style;..) pour différencier le nom du produit et la marque (plutôt que des parenthèses) 
- [x] Pareil pour le pseudo, une couleur ou quelque chose de bien visible
- [x] Si utilisateur n'a pas d'image de sa mesure, ajouter une image de pigeon sur une balance (par exemple) par défaut pour le coté visuel → see #82
- [x] Contribuer : sur cette page les images doivent avoir un lien avec le projet, des pigeons, des pigeons, encore des pigeons. Ou des sacs de farine, ou de sucre...
> 
>     Pesez !
>     La première et la plus importantes des contributions que vous puissiez faire est de peser vos courses et de partager vos résultats ici même ! C'est l'ensemble de toutes les mesures ainsi récupérées qui font l'intérêt de ce site et permettentd'élaborer les jolies statistiques qui vous aideront à mieux choisir vos produits en magasin... et à dénoncer ces pratiques irrespectueuses des consomma(c)teurs
>     Sur Github
>     Vous aimez ce site mais vous avez trouvé un bug ? Vous avez une idée de fonctionnalité qui manque ? Vous pensez qu'il est possible d'améliorer les fonctionnalités existante ? Alors n'hésitez pas à nous proposer votre idée via la page contact ou sur le dépôt Github du projet ! (Et même la programmer avec nous si vous le souhaitez !)
- [x] vie privée : a caser ailleurs dans un coin plus discret, ou en dernier
- [x] enlever la notification "danger zone" la ou on désactive son compte
- [x] Poids sur le paquet on arrondi pour obtenir 900g plutôt que 900.0g ça pollue visuellement
- [x] Enlève l'heure à laquelle la mesure a été ajoutée, on s'en fiche ça pollue visuellement pour rien

### Trad
 - [x] Une version complètement française (added by, last mesures, dates...), une autre complètement anglaise (FR/EN discret en haut à droite de la page d'accueil)
 - [x] Proposition pour l'intro :
> Répondre à cette question est l'objectif de ce site. Tout commence lorsqu'une connaissance nous lance « J'ai pesé mon pâquet de 1kg de riz, bah il faisait 960g ! ». Et l'expérience s'est réitérée plusieurs fois. L'idée fait son chemin... Pourquoi ne pas créer une base de donnée rassemblant toutes ces mesures et découvrir à quel point on se fait pigeonner ? 

### Full feature
 - [x] Ajouter un vrai formulaire de contact : Vous êtes journaliste et vous voulez parler de nous ? N'hésitez pas à nous contacter via ce formulaire ! → see #81 
 - [x] Pseudos cliquable avec des profils publiques affichant les stats des users (nombres de mesures sur combien de produits/marques) → see #80
